spring.application.name=example2


spring.security.oauth2.client.registration.google.client-id=b
spring.security.oauth2.client.registration.google.client-secret=a
spring.security.oauth2.client.registration.google.scope=openid,profile,email,https://www.googleapis.com/auth/youtube
#
# spring.securityoauth2:client:registration.google.clientId: sdfds

